version: '3'
services:
  influxdb:
    image: influxdb:alpine
    ports:
      - 8086:8086
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
    ports:
      - 3000:3000
  agent:
    build: ./Dockerfile
    environment:
      - INFLUXDB_SERVER=http://influxdb:8086
    depends_on:
      - influxdb